name: CI for NestJS Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci --force

      - name: Run TypeScript type checking
        run: npm run typescript:check

      - name: Run Prettier
        run: npm run format

      - name: Run tests
        run: npm run test

      - name: Build the application
        run: npm run build

  Continuous-Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: .
        run: docker build -t my-backend .

      - name: Run Tests in Docker
        working-directory: .
        run: docker run --rm my-backend npm test
