name: CI for NestJS Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --force

      - name: Run TypeScript type checking
        run: npm run typescript:check

      # Lint the code
      - name: Run ESLint
        run: npm run lint

      # Format the code
      - name: Run Prettier
        run: npm run format

      # Run tests
      - name: Run tests
        run: npm run test

      # Build the application
      - name: Build the application
        run: npm run build
